    EggertData us up   data (precompressed liquid he) init dense = 3.5 ; 2.3 ; 1.8 ; 1.5 ; 1


    Name hug_0171 Curve HugPres Mat D2 P 1e-4:800:200:1 StartR 0.171 StartE 0.1  Out R:P 
    Name t077     Curve P_RT   Mat D2 R 1e-5:3:288:1 T 77     Out R:P 
    Name t3       Curve P_RT   Mat D2 R 1e-5:3:288:1 T 3000   Out R:P 
    Name t10      Curve P_RT   Mat D2 R 1e-5:3:288:1 T 10000  Out R:P 
